from flutter_utils.material_icons_parser.material_icons_specs_utils import parse_as_icons_spec


# e.g. -> static readonly person: RemoteIconData = RemoteIconData.fromMaterial("person");
TS_REMOTE_ICON_DATA_LINE_TEMPLATE = """\"{icon_name}\""""


def generate_ts_material_icons_type_source():
    file_text = """
// generated by ts_lib_builder.py
"""
    spec = parse_as_icons_spec()
    defs = []
    for s in spec:
        icon_name = s["name"]
        defs.append(TS_REMOTE_ICON_DATA_LINE_TEMPLATE.format(
            icon_name=icon_name))
    defline = "type IconNames = " + " | ".join(defs) + ";"
    return file_text + "\n" + defline


if __name__ == "__main__":
    f = generate_ts_material_icons_type_source()
    print(f)
