# builder for https://github.com/bridgedxyz/flutter-builder - material/icons
from flutter_utils.material_icons_parser.material_icons_specs_utils import parse_as_icons_spec



def generate_ts_material_icons_class_source():
    file_text = """
// generated by ts_lib_builder.py
"""
    spec = parse_as_icons_spec()
    for s in spec:
        icon_name = s["name"]
        line = f"""static get {icon_name}(): IconData {{ return new IconData().overrideSnippet("Icons.{icon_name}"); }}\n"""
        file_text += line
    print(file_text)
    return file_text


if __name__ == "__main__":
    generate_ts_material_icons_class_source()
