
import {RemoteIconData} from "./index";

// generated by ts_lib_builder.py
export class MaterialIcons {


    static readonly threesixty: RemoteIconData = RemoteIconData.fromMaterial("threesixty");


    static readonly threed_rotation: RemoteIconData = RemoteIconData.fromMaterial("threed_rotation");


    static readonly four_k: RemoteIconData = RemoteIconData.fromMaterial("four_k");


    static readonly ac_unit: RemoteIconData = RemoteIconData.fromMaterial("ac_unit");


    static readonly access_alarm: RemoteIconData = RemoteIconData.fromMaterial("access_alarm");


    static readonly access_alarms: RemoteIconData = RemoteIconData.fromMaterial("access_alarms");


    static readonly access_time: RemoteIconData = RemoteIconData.fromMaterial("access_time");


    static readonly accessibility: RemoteIconData = RemoteIconData.fromMaterial("accessibility");


    static readonly accessibility_new: RemoteIconData = RemoteIconData.fromMaterial("accessibility_new");


    static readonly accessible: RemoteIconData = RemoteIconData.fromMaterial("accessible");


    static readonly accessible_forward: RemoteIconData = RemoteIconData.fromMaterial("accessible_forward");


    static readonly account_balance: RemoteIconData = RemoteIconData.fromMaterial("account_balance");


    static readonly account_balance_wallet: RemoteIconData = RemoteIconData.fromMaterial("account_balance_wallet");


    static readonly account_box: RemoteIconData = RemoteIconData.fromMaterial("account_box");


    static readonly account_circle: RemoteIconData = RemoteIconData.fromMaterial("account_circle");


    static readonly adb: RemoteIconData = RemoteIconData.fromMaterial("adb");


    static readonly add: RemoteIconData = RemoteIconData.fromMaterial("add");


    static readonly add_a_photo: RemoteIconData = RemoteIconData.fromMaterial("add_a_photo");


    static readonly add_alarm: RemoteIconData = RemoteIconData.fromMaterial("add_alarm");


    static readonly add_alert: RemoteIconData = RemoteIconData.fromMaterial("add_alert");


    static readonly add_box: RemoteIconData = RemoteIconData.fromMaterial("add_box");


    static readonly add_call: RemoteIconData = RemoteIconData.fromMaterial("add_call");


    static readonly add_circle: RemoteIconData = RemoteIconData.fromMaterial("add_circle");


    static readonly add_circle_outline: RemoteIconData = RemoteIconData.fromMaterial("add_circle_outline");


    static readonly add_comment: RemoteIconData = RemoteIconData.fromMaterial("add_comment");


    static readonly add_location: RemoteIconData = RemoteIconData.fromMaterial("add_location");


    static readonly add_photo_alternate: RemoteIconData = RemoteIconData.fromMaterial("add_photo_alternate");


    static readonly add_shopping_cart: RemoteIconData = RemoteIconData.fromMaterial("add_shopping_cart");


    static readonly add_to_home_screen: RemoteIconData = RemoteIconData.fromMaterial("add_to_home_screen");


    static readonly add_to_photos: RemoteIconData = RemoteIconData.fromMaterial("add_to_photos");


    static readonly add_to_queue: RemoteIconData = RemoteIconData.fromMaterial("add_to_queue");


    static readonly adjust: RemoteIconData = RemoteIconData.fromMaterial("adjust");


    static readonly airline_seat_flat: RemoteIconData = RemoteIconData.fromMaterial("airline_seat_flat");


    static readonly airline_seat_flat_angled: RemoteIconData = RemoteIconData.fromMaterial("airline_seat_flat_angled");


    static readonly airline_seat_individual_suite: RemoteIconData = RemoteIconData.fromMaterial("airline_seat_individual_suite");


    static readonly airline_seat_legroom_extra: RemoteIconData = RemoteIconData.fromMaterial("airline_seat_legroom_extra");


    static readonly airline_seat_legroom_normal: RemoteIconData = RemoteIconData.fromMaterial("airline_seat_legroom_normal");


    static readonly airline_seat_legroom_reduced: RemoteIconData = RemoteIconData.fromMaterial("airline_seat_legroom_reduced");


    static readonly airline_seat_recline_extra: RemoteIconData = RemoteIconData.fromMaterial("airline_seat_recline_extra");


    static readonly airline_seat_recline_normal: RemoteIconData = RemoteIconData.fromMaterial("airline_seat_recline_normal");


    static readonly airplanemode_active: RemoteIconData = RemoteIconData.fromMaterial("airplanemode_active");


    static readonly airplanemode_inactive: RemoteIconData = RemoteIconData.fromMaterial("airplanemode_inactive");


    static readonly airplay: RemoteIconData = RemoteIconData.fromMaterial("airplay");


    static readonly airport_shuttle: RemoteIconData = RemoteIconData.fromMaterial("airport_shuttle");


    static readonly alarm: RemoteIconData = RemoteIconData.fromMaterial("alarm");


    static readonly alarm_add: RemoteIconData = RemoteIconData.fromMaterial("alarm_add");


    static readonly alarm_off: RemoteIconData = RemoteIconData.fromMaterial("alarm_off");


    static readonly alarm_on: RemoteIconData = RemoteIconData.fromMaterial("alarm_on");


    static readonly album: RemoteIconData = RemoteIconData.fromMaterial("album");


    static readonly all_inclusive: RemoteIconData = RemoteIconData.fromMaterial("all_inclusive");


    static readonly all_out: RemoteIconData = RemoteIconData.fromMaterial("all_out");


    static readonly alternate_email: RemoteIconData = RemoteIconData.fromMaterial("alternate_email");


    static readonly android: RemoteIconData = RemoteIconData.fromMaterial("android");


    static readonly announcement: RemoteIconData = RemoteIconData.fromMaterial("announcement");


    static readonly apps: RemoteIconData = RemoteIconData.fromMaterial("apps");


    static readonly archive: RemoteIconData = RemoteIconData.fromMaterial("archive");


    static readonly arrow_back: RemoteIconData = RemoteIconData.fromMaterial("arrow_back");


    static readonly arrow_back_ios: RemoteIconData = RemoteIconData.fromMaterial("arrow_back_ios");


    static readonly arrow_downward: RemoteIconData = RemoteIconData.fromMaterial("arrow_downward");


    static readonly arrow_drop_down: RemoteIconData = RemoteIconData.fromMaterial("arrow_drop_down");


    static readonly arrow_drop_down_circle: RemoteIconData = RemoteIconData.fromMaterial("arrow_drop_down_circle");


    static readonly arrow_drop_up: RemoteIconData = RemoteIconData.fromMaterial("arrow_drop_up");


    static readonly arrow_forward: RemoteIconData = RemoteIconData.fromMaterial("arrow_forward");


    static readonly arrow_forward_ios: RemoteIconData = RemoteIconData.fromMaterial("arrow_forward_ios");


    static readonly arrow_left: RemoteIconData = RemoteIconData.fromMaterial("arrow_left");


    static readonly arrow_right: RemoteIconData = RemoteIconData.fromMaterial("arrow_right");


    static readonly arrow_upward: RemoteIconData = RemoteIconData.fromMaterial("arrow_upward");


    static readonly art_track: RemoteIconData = RemoteIconData.fromMaterial("art_track");


    static readonly aspect_ratio: RemoteIconData = RemoteIconData.fromMaterial("aspect_ratio");


    static readonly assessment: RemoteIconData = RemoteIconData.fromMaterial("assessment");


    static readonly assignment: RemoteIconData = RemoteIconData.fromMaterial("assignment");


    static readonly assignment_ind: RemoteIconData = RemoteIconData.fromMaterial("assignment_ind");


    static readonly assignment_late: RemoteIconData = RemoteIconData.fromMaterial("assignment_late");


    static readonly assignment_return: RemoteIconData = RemoteIconData.fromMaterial("assignment_return");


    static readonly assignment_returned: RemoteIconData = RemoteIconData.fromMaterial("assignment_returned");


    static readonly assignment_turned_in: RemoteIconData = RemoteIconData.fromMaterial("assignment_turned_in");


    static readonly assistant: RemoteIconData = RemoteIconData.fromMaterial("assistant");


    static readonly assistant_photo: RemoteIconData = RemoteIconData.fromMaterial("assistant_photo");


    static readonly atm: RemoteIconData = RemoteIconData.fromMaterial("atm");


    static readonly attach_file: RemoteIconData = RemoteIconData.fromMaterial("attach_file");


    static readonly attach_money: RemoteIconData = RemoteIconData.fromMaterial("attach_money");


    static readonly attachment: RemoteIconData = RemoteIconData.fromMaterial("attachment");


    static readonly audiotrack: RemoteIconData = RemoteIconData.fromMaterial("audiotrack");


    static readonly autorenew: RemoteIconData = RemoteIconData.fromMaterial("autorenew");


    static readonly av_timer: RemoteIconData = RemoteIconData.fromMaterial("av_timer");


    static readonly backspace: RemoteIconData = RemoteIconData.fromMaterial("backspace");


    static readonly backup: RemoteIconData = RemoteIconData.fromMaterial("backup");


    static readonly battery_alert: RemoteIconData = RemoteIconData.fromMaterial("battery_alert");


    static readonly battery_charging_full: RemoteIconData = RemoteIconData.fromMaterial("battery_charging_full");


    static readonly battery_full: RemoteIconData = RemoteIconData.fromMaterial("battery_full");


    static readonly battery_std: RemoteIconData = RemoteIconData.fromMaterial("battery_std");


    static readonly battery_unknown: RemoteIconData = RemoteIconData.fromMaterial("battery_unknown");


    static readonly beach_access: RemoteIconData = RemoteIconData.fromMaterial("beach_access");


    static readonly beenhere: RemoteIconData = RemoteIconData.fromMaterial("beenhere");


    static readonly block: RemoteIconData = RemoteIconData.fromMaterial("block");


    static readonly bluetooth: RemoteIconData = RemoteIconData.fromMaterial("bluetooth");


    static readonly bluetooth_audio: RemoteIconData = RemoteIconData.fromMaterial("bluetooth_audio");


    static readonly bluetooth_connected: RemoteIconData = RemoteIconData.fromMaterial("bluetooth_connected");


    static readonly bluetooth_disabled: RemoteIconData = RemoteIconData.fromMaterial("bluetooth_disabled");


    static readonly bluetooth_searching: RemoteIconData = RemoteIconData.fromMaterial("bluetooth_searching");


    static readonly blur_circular: RemoteIconData = RemoteIconData.fromMaterial("blur_circular");


    static readonly blur_linear: RemoteIconData = RemoteIconData.fromMaterial("blur_linear");


    static readonly blur_off: RemoteIconData = RemoteIconData.fromMaterial("blur_off");


    static readonly blur_on: RemoteIconData = RemoteIconData.fromMaterial("blur_on");


    static readonly book: RemoteIconData = RemoteIconData.fromMaterial("book");


    static readonly bookmark: RemoteIconData = RemoteIconData.fromMaterial("bookmark");


    static readonly bookmark_border: RemoteIconData = RemoteIconData.fromMaterial("bookmark_border");


    static readonly border_all: RemoteIconData = RemoteIconData.fromMaterial("border_all");


    static readonly border_bottom: RemoteIconData = RemoteIconData.fromMaterial("border_bottom");


    static readonly border_clear: RemoteIconData = RemoteIconData.fromMaterial("border_clear");


    static readonly border_color: RemoteIconData = RemoteIconData.fromMaterial("border_color");


    static readonly border_horizontal: RemoteIconData = RemoteIconData.fromMaterial("border_horizontal");


    static readonly border_inner: RemoteIconData = RemoteIconData.fromMaterial("border_inner");


    static readonly border_left: RemoteIconData = RemoteIconData.fromMaterial("border_left");


    static readonly border_outer: RemoteIconData = RemoteIconData.fromMaterial("border_outer");


    static readonly border_right: RemoteIconData = RemoteIconData.fromMaterial("border_right");


    static readonly border_style: RemoteIconData = RemoteIconData.fromMaterial("border_style");


    static readonly border_top: RemoteIconData = RemoteIconData.fromMaterial("border_top");


    static readonly border_vertical: RemoteIconData = RemoteIconData.fromMaterial("border_vertical");


    static readonly branding_watermark: RemoteIconData = RemoteIconData.fromMaterial("branding_watermark");


    static readonly brightness_1: RemoteIconData = RemoteIconData.fromMaterial("brightness_1");


    static readonly brightness_2: RemoteIconData = RemoteIconData.fromMaterial("brightness_2");


    static readonly brightness_3: RemoteIconData = RemoteIconData.fromMaterial("brightness_3");


    static readonly brightness_4: RemoteIconData = RemoteIconData.fromMaterial("brightness_4");


    static readonly brightness_5: RemoteIconData = RemoteIconData.fromMaterial("brightness_5");


    static readonly brightness_6: RemoteIconData = RemoteIconData.fromMaterial("brightness_6");


    static readonly brightness_7: RemoteIconData = RemoteIconData.fromMaterial("brightness_7");


    static readonly brightness_auto: RemoteIconData = RemoteIconData.fromMaterial("brightness_auto");


    static readonly brightness_high: RemoteIconData = RemoteIconData.fromMaterial("brightness_high");


    static readonly brightness_low: RemoteIconData = RemoteIconData.fromMaterial("brightness_low");


    static readonly brightness_medium: RemoteIconData = RemoteIconData.fromMaterial("brightness_medium");


    static readonly broken_image: RemoteIconData = RemoteIconData.fromMaterial("broken_image");


    static readonly brush: RemoteIconData = RemoteIconData.fromMaterial("brush");


    static readonly bubble_chart: RemoteIconData = RemoteIconData.fromMaterial("bubble_chart");


    static readonly bug_report: RemoteIconData = RemoteIconData.fromMaterial("bug_report");


    static readonly build: RemoteIconData = RemoteIconData.fromMaterial("build");


    static readonly burst_mode: RemoteIconData = RemoteIconData.fromMaterial("burst_mode");


    static readonly business: RemoteIconData = RemoteIconData.fromMaterial("business");


    static readonly business_center: RemoteIconData = RemoteIconData.fromMaterial("business_center");


    static readonly cached: RemoteIconData = RemoteIconData.fromMaterial("cached");


    static readonly cake: RemoteIconData = RemoteIconData.fromMaterial("cake");


    static readonly calendar_today: RemoteIconData = RemoteIconData.fromMaterial("calendar_today");


    static readonly calendar_view_day: RemoteIconData = RemoteIconData.fromMaterial("calendar_view_day");


    static readonly call: RemoteIconData = RemoteIconData.fromMaterial("call");


    static readonly call_end: RemoteIconData = RemoteIconData.fromMaterial("call_end");


    static readonly call_made: RemoteIconData = RemoteIconData.fromMaterial("call_made");


    static readonly call_merge: RemoteIconData = RemoteIconData.fromMaterial("call_merge");


    static readonly call_missed: RemoteIconData = RemoteIconData.fromMaterial("call_missed");


    static readonly call_missed_outgoing: RemoteIconData = RemoteIconData.fromMaterial("call_missed_outgoing");


    static readonly call_received: RemoteIconData = RemoteIconData.fromMaterial("call_received");


    static readonly call_split: RemoteIconData = RemoteIconData.fromMaterial("call_split");


    static readonly call_to_action: RemoteIconData = RemoteIconData.fromMaterial("call_to_action");


    static readonly camera: RemoteIconData = RemoteIconData.fromMaterial("camera");


    static readonly camera_alt: RemoteIconData = RemoteIconData.fromMaterial("camera_alt");


    static readonly camera_enhance: RemoteIconData = RemoteIconData.fromMaterial("camera_enhance");


    static readonly camera_front: RemoteIconData = RemoteIconData.fromMaterial("camera_front");


    static readonly camera_rear: RemoteIconData = RemoteIconData.fromMaterial("camera_rear");


    static readonly camera_roll: RemoteIconData = RemoteIconData.fromMaterial("camera_roll");


    static readonly cancel: RemoteIconData = RemoteIconData.fromMaterial("cancel");


    static readonly card_giftcard: RemoteIconData = RemoteIconData.fromMaterial("card_giftcard");


    static readonly card_membership: RemoteIconData = RemoteIconData.fromMaterial("card_membership");


    static readonly card_travel: RemoteIconData = RemoteIconData.fromMaterial("card_travel");


    static readonly casino: RemoteIconData = RemoteIconData.fromMaterial("casino");


    static readonly cast: RemoteIconData = RemoteIconData.fromMaterial("cast");


    static readonly cast_connected: RemoteIconData = RemoteIconData.fromMaterial("cast_connected");


    static readonly category: RemoteIconData = RemoteIconData.fromMaterial("category");


    static readonly center_focus_strong: RemoteIconData = RemoteIconData.fromMaterial("center_focus_strong");


    static readonly center_focus_weak: RemoteIconData = RemoteIconData.fromMaterial("center_focus_weak");


    static readonly change_history: RemoteIconData = RemoteIconData.fromMaterial("change_history");


    static readonly chat: RemoteIconData = RemoteIconData.fromMaterial("chat");


    static readonly chat_bubble: RemoteIconData = RemoteIconData.fromMaterial("chat_bubble");


    static readonly chat_bubble_outline: RemoteIconData = RemoteIconData.fromMaterial("chat_bubble_outline");


    static readonly check: RemoteIconData = RemoteIconData.fromMaterial("check");


    static readonly check_box: RemoteIconData = RemoteIconData.fromMaterial("check_box");


    static readonly check_box_outline_blank: RemoteIconData = RemoteIconData.fromMaterial("check_box_outline_blank");


    static readonly check_circle: RemoteIconData = RemoteIconData.fromMaterial("check_circle");


    static readonly check_circle_outline: RemoteIconData = RemoteIconData.fromMaterial("check_circle_outline");


    static readonly chevron_left: RemoteIconData = RemoteIconData.fromMaterial("chevron_left");


    static readonly chevron_right: RemoteIconData = RemoteIconData.fromMaterial("chevron_right");


    static readonly child_care: RemoteIconData = RemoteIconData.fromMaterial("child_care");


    static readonly child_friendly: RemoteIconData = RemoteIconData.fromMaterial("child_friendly");


    static readonly chrome_reader_mode: RemoteIconData = RemoteIconData.fromMaterial("chrome_reader_mode");


    static readonly class_: RemoteIconData = RemoteIconData.fromMaterial("class_");


    static readonly clear: RemoteIconData = RemoteIconData.fromMaterial("clear");


    static readonly clear_all: RemoteIconData = RemoteIconData.fromMaterial("clear_all");


    static readonly close: RemoteIconData = RemoteIconData.fromMaterial("close");


    static readonly closed_caption: RemoteIconData = RemoteIconData.fromMaterial("closed_caption");


    static readonly cloud: RemoteIconData = RemoteIconData.fromMaterial("cloud");


    static readonly cloud_circle: RemoteIconData = RemoteIconData.fromMaterial("cloud_circle");


    static readonly cloud_done: RemoteIconData = RemoteIconData.fromMaterial("cloud_done");


    static readonly cloud_download: RemoteIconData = RemoteIconData.fromMaterial("cloud_download");


    static readonly cloud_off: RemoteIconData = RemoteIconData.fromMaterial("cloud_off");


    static readonly cloud_queue: RemoteIconData = RemoteIconData.fromMaterial("cloud_queue");


    static readonly cloud_upload: RemoteIconData = RemoteIconData.fromMaterial("cloud_upload");


    static readonly code: RemoteIconData = RemoteIconData.fromMaterial("code");


    static readonly collections: RemoteIconData = RemoteIconData.fromMaterial("collections");


    static readonly collections_bookmark: RemoteIconData = RemoteIconData.fromMaterial("collections_bookmark");


    static readonly color_lens: RemoteIconData = RemoteIconData.fromMaterial("color_lens");


    static readonly colorize: RemoteIconData = RemoteIconData.fromMaterial("colorize");


    static readonly comment: RemoteIconData = RemoteIconData.fromMaterial("comment");


    static readonly compare: RemoteIconData = RemoteIconData.fromMaterial("compare");


    static readonly compare_arrows: RemoteIconData = RemoteIconData.fromMaterial("compare_arrows");


    static readonly computer: RemoteIconData = RemoteIconData.fromMaterial("computer");


    static readonly confirmation_number: RemoteIconData = RemoteIconData.fromMaterial("confirmation_number");


    static readonly contact_mail: RemoteIconData = RemoteIconData.fromMaterial("contact_mail");


    static readonly contact_phone: RemoteIconData = RemoteIconData.fromMaterial("contact_phone");


    static readonly contacts: RemoteIconData = RemoteIconData.fromMaterial("contacts");


    static readonly content_copy: RemoteIconData = RemoteIconData.fromMaterial("content_copy");


    static readonly content_cut: RemoteIconData = RemoteIconData.fromMaterial("content_cut");


    static readonly content_paste: RemoteIconData = RemoteIconData.fromMaterial("content_paste");


    static readonly control_point: RemoteIconData = RemoteIconData.fromMaterial("control_point");


    static readonly control_point_duplicate: RemoteIconData = RemoteIconData.fromMaterial("control_point_duplicate");


    static readonly copyright: RemoteIconData = RemoteIconData.fromMaterial("copyright");


    static readonly create: RemoteIconData = RemoteIconData.fromMaterial("create");


    static readonly create_new_folder: RemoteIconData = RemoteIconData.fromMaterial("create_new_folder");


    static readonly credit_card: RemoteIconData = RemoteIconData.fromMaterial("credit_card");


    static readonly crop: RemoteIconData = RemoteIconData.fromMaterial("crop");


    static readonly crop_16_9: RemoteIconData = RemoteIconData.fromMaterial("crop_16_9");


    static readonly crop_3_2: RemoteIconData = RemoteIconData.fromMaterial("crop_3_2");


    static readonly crop_5_4: RemoteIconData = RemoteIconData.fromMaterial("crop_5_4");


    static readonly crop_7_5: RemoteIconData = RemoteIconData.fromMaterial("crop_7_5");


    static readonly crop_din: RemoteIconData = RemoteIconData.fromMaterial("crop_din");


    static readonly crop_free: RemoteIconData = RemoteIconData.fromMaterial("crop_free");


    static readonly crop_landscape: RemoteIconData = RemoteIconData.fromMaterial("crop_landscape");


    static readonly crop_original: RemoteIconData = RemoteIconData.fromMaterial("crop_original");


    static readonly crop_portrait: RemoteIconData = RemoteIconData.fromMaterial("crop_portrait");


    static readonly crop_rotate: RemoteIconData = RemoteIconData.fromMaterial("crop_rotate");


    static readonly crop_square: RemoteIconData = RemoteIconData.fromMaterial("crop_square");


    static readonly dashboard: RemoteIconData = RemoteIconData.fromMaterial("dashboard");


    static readonly data_usage: RemoteIconData = RemoteIconData.fromMaterial("data_usage");


    static readonly date_range: RemoteIconData = RemoteIconData.fromMaterial("date_range");


    static readonly dehaze: RemoteIconData = RemoteIconData.fromMaterial("dehaze");


    static readonly delete: RemoteIconData = RemoteIconData.fromMaterial("delete");


    static readonly delete_forever: RemoteIconData = RemoteIconData.fromMaterial("delete_forever");


    static readonly delete_outline: RemoteIconData = RemoteIconData.fromMaterial("delete_outline");


    static readonly delete_sweep: RemoteIconData = RemoteIconData.fromMaterial("delete_sweep");


    static readonly departure_board: RemoteIconData = RemoteIconData.fromMaterial("departure_board");


    static readonly description: RemoteIconData = RemoteIconData.fromMaterial("description");


    static readonly desktop_mac: RemoteIconData = RemoteIconData.fromMaterial("desktop_mac");


    static readonly desktop_windows: RemoteIconData = RemoteIconData.fromMaterial("desktop_windows");


    static readonly details: RemoteIconData = RemoteIconData.fromMaterial("details");


    static readonly developer_board: RemoteIconData = RemoteIconData.fromMaterial("developer_board");


    static readonly developer_mode: RemoteIconData = RemoteIconData.fromMaterial("developer_mode");


    static readonly device_hub: RemoteIconData = RemoteIconData.fromMaterial("device_hub");


    static readonly device_unknown: RemoteIconData = RemoteIconData.fromMaterial("device_unknown");


    static readonly devices: RemoteIconData = RemoteIconData.fromMaterial("devices");


    static readonly devices_other: RemoteIconData = RemoteIconData.fromMaterial("devices_other");


    static readonly dialer_sip: RemoteIconData = RemoteIconData.fromMaterial("dialer_sip");


    static readonly dialpad: RemoteIconData = RemoteIconData.fromMaterial("dialpad");


    static readonly directions: RemoteIconData = RemoteIconData.fromMaterial("directions");


    static readonly directions_bike: RemoteIconData = RemoteIconData.fromMaterial("directions_bike");


    static readonly directions_boat: RemoteIconData = RemoteIconData.fromMaterial("directions_boat");


    static readonly directions_bus: RemoteIconData = RemoteIconData.fromMaterial("directions_bus");


    static readonly directions_car: RemoteIconData = RemoteIconData.fromMaterial("directions_car");


    static readonly directions_railway: RemoteIconData = RemoteIconData.fromMaterial("directions_railway");


    static readonly directions_run: RemoteIconData = RemoteIconData.fromMaterial("directions_run");


    static readonly directions_subway: RemoteIconData = RemoteIconData.fromMaterial("directions_subway");


    static readonly directions_transit: RemoteIconData = RemoteIconData.fromMaterial("directions_transit");


    static readonly directions_walk: RemoteIconData = RemoteIconData.fromMaterial("directions_walk");


    static readonly disc_full: RemoteIconData = RemoteIconData.fromMaterial("disc_full");


    static readonly dns: RemoteIconData = RemoteIconData.fromMaterial("dns");


    static readonly do_not_disturb: RemoteIconData = RemoteIconData.fromMaterial("do_not_disturb");


    static readonly do_not_disturb_alt: RemoteIconData = RemoteIconData.fromMaterial("do_not_disturb_alt");


    static readonly do_not_disturb_off: RemoteIconData = RemoteIconData.fromMaterial("do_not_disturb_off");


    static readonly do_not_disturb_on: RemoteIconData = RemoteIconData.fromMaterial("do_not_disturb_on");


    static readonly dock: RemoteIconData = RemoteIconData.fromMaterial("dock");


    static readonly domain: RemoteIconData = RemoteIconData.fromMaterial("domain");


    static readonly done: RemoteIconData = RemoteIconData.fromMaterial("done");


    static readonly done_all: RemoteIconData = RemoteIconData.fromMaterial("done_all");


    static readonly done_outline: RemoteIconData = RemoteIconData.fromMaterial("done_outline");


    static readonly donut_large: RemoteIconData = RemoteIconData.fromMaterial("donut_large");


    static readonly donut_small: RemoteIconData = RemoteIconData.fromMaterial("donut_small");


    static readonly drafts: RemoteIconData = RemoteIconData.fromMaterial("drafts");


    static readonly drag_handle: RemoteIconData = RemoteIconData.fromMaterial("drag_handle");


    static readonly drive_eta: RemoteIconData = RemoteIconData.fromMaterial("drive_eta");


    static readonly dvr: RemoteIconData = RemoteIconData.fromMaterial("dvr");


    static readonly edit: RemoteIconData = RemoteIconData.fromMaterial("edit");


    static readonly edit_attributes: RemoteIconData = RemoteIconData.fromMaterial("edit_attributes");


    static readonly edit_location: RemoteIconData = RemoteIconData.fromMaterial("edit_location");


    static readonly eject: RemoteIconData = RemoteIconData.fromMaterial("eject");


    static readonly email: RemoteIconData = RemoteIconData.fromMaterial("email");


    static readonly enhanced_encryption: RemoteIconData = RemoteIconData.fromMaterial("enhanced_encryption");


    static readonly equalizer: RemoteIconData = RemoteIconData.fromMaterial("equalizer");


    static readonly error: RemoteIconData = RemoteIconData.fromMaterial("error");


    static readonly error_outline: RemoteIconData = RemoteIconData.fromMaterial("error_outline");


    static readonly euro_symbol: RemoteIconData = RemoteIconData.fromMaterial("euro_symbol");


    static readonly ev_station: RemoteIconData = RemoteIconData.fromMaterial("ev_station");


    static readonly event: RemoteIconData = RemoteIconData.fromMaterial("event");


    static readonly event_available: RemoteIconData = RemoteIconData.fromMaterial("event_available");


    static readonly event_busy: RemoteIconData = RemoteIconData.fromMaterial("event_busy");


    static readonly event_note: RemoteIconData = RemoteIconData.fromMaterial("event_note");


    static readonly event_seat: RemoteIconData = RemoteIconData.fromMaterial("event_seat");


    static readonly exit_to_app: RemoteIconData = RemoteIconData.fromMaterial("exit_to_app");


    static readonly expand_less: RemoteIconData = RemoteIconData.fromMaterial("expand_less");


    static readonly expand_more: RemoteIconData = RemoteIconData.fromMaterial("expand_more");


    static readonly explicit: RemoteIconData = RemoteIconData.fromMaterial("explicit");


    static readonly explore: RemoteIconData = RemoteIconData.fromMaterial("explore");


    static readonly exposure: RemoteIconData = RemoteIconData.fromMaterial("exposure");


    static readonly exposure_neg_1: RemoteIconData = RemoteIconData.fromMaterial("exposure_neg_1");


    static readonly exposure_neg_2: RemoteIconData = RemoteIconData.fromMaterial("exposure_neg_2");


    static readonly exposure_plus_1: RemoteIconData = RemoteIconData.fromMaterial("exposure_plus_1");


    static readonly exposure_plus_2: RemoteIconData = RemoteIconData.fromMaterial("exposure_plus_2");


    static readonly exposure_zero: RemoteIconData = RemoteIconData.fromMaterial("exposure_zero");


    static readonly extension: RemoteIconData = RemoteIconData.fromMaterial("extension");


    static readonly face: RemoteIconData = RemoteIconData.fromMaterial("face");


    static readonly fast_forward: RemoteIconData = RemoteIconData.fromMaterial("fast_forward");


    static readonly fast_rewind: RemoteIconData = RemoteIconData.fromMaterial("fast_rewind");


    static readonly fastfood: RemoteIconData = RemoteIconData.fromMaterial("fastfood");


    static readonly favorite: RemoteIconData = RemoteIconData.fromMaterial("favorite");


    static readonly favorite_border: RemoteIconData = RemoteIconData.fromMaterial("favorite_border");


    static readonly featured_play_list: RemoteIconData = RemoteIconData.fromMaterial("featured_play_list");


    static readonly featured_video: RemoteIconData = RemoteIconData.fromMaterial("featured_video");


    static readonly feedback: RemoteIconData = RemoteIconData.fromMaterial("feedback");


    static readonly fiber_dvr: RemoteIconData = RemoteIconData.fromMaterial("fiber_dvr");


    static readonly fiber_manual_record: RemoteIconData = RemoteIconData.fromMaterial("fiber_manual_record");


    static readonly fiber_new: RemoteIconData = RemoteIconData.fromMaterial("fiber_new");


    static readonly fiber_pin: RemoteIconData = RemoteIconData.fromMaterial("fiber_pin");


    static readonly fiber_smart_record: RemoteIconData = RemoteIconData.fromMaterial("fiber_smart_record");


    static readonly file_download: RemoteIconData = RemoteIconData.fromMaterial("file_download");


    static readonly file_upload: RemoteIconData = RemoteIconData.fromMaterial("file_upload");


    static readonly filter: RemoteIconData = RemoteIconData.fromMaterial("filter");


    static readonly filter_1: RemoteIconData = RemoteIconData.fromMaterial("filter_1");


    static readonly filter_2: RemoteIconData = RemoteIconData.fromMaterial("filter_2");


    static readonly filter_3: RemoteIconData = RemoteIconData.fromMaterial("filter_3");


    static readonly filter_4: RemoteIconData = RemoteIconData.fromMaterial("filter_4");


    static readonly filter_5: RemoteIconData = RemoteIconData.fromMaterial("filter_5");


    static readonly filter_6: RemoteIconData = RemoteIconData.fromMaterial("filter_6");


    static readonly filter_7: RemoteIconData = RemoteIconData.fromMaterial("filter_7");


    static readonly filter_8: RemoteIconData = RemoteIconData.fromMaterial("filter_8");


    static readonly filter_9: RemoteIconData = RemoteIconData.fromMaterial("filter_9");


    static readonly filter_9_plus: RemoteIconData = RemoteIconData.fromMaterial("filter_9_plus");


    static readonly filter_b_and_w: RemoteIconData = RemoteIconData.fromMaterial("filter_b_and_w");


    static readonly filter_center_focus: RemoteIconData = RemoteIconData.fromMaterial("filter_center_focus");


    static readonly filter_drama: RemoteIconData = RemoteIconData.fromMaterial("filter_drama");


    static readonly filter_frames: RemoteIconData = RemoteIconData.fromMaterial("filter_frames");


    static readonly filter_hdr: RemoteIconData = RemoteIconData.fromMaterial("filter_hdr");


    static readonly filter_list: RemoteIconData = RemoteIconData.fromMaterial("filter_list");


    static readonly filter_none: RemoteIconData = RemoteIconData.fromMaterial("filter_none");


    static readonly filter_tilt_shift: RemoteIconData = RemoteIconData.fromMaterial("filter_tilt_shift");


    static readonly filter_vintage: RemoteIconData = RemoteIconData.fromMaterial("filter_vintage");


    static readonly find_in_page: RemoteIconData = RemoteIconData.fromMaterial("find_in_page");


    static readonly find_replace: RemoteIconData = RemoteIconData.fromMaterial("find_replace");


    static readonly fingerprint: RemoteIconData = RemoteIconData.fromMaterial("fingerprint");


    static readonly first_page: RemoteIconData = RemoteIconData.fromMaterial("first_page");


    static readonly fitness_center: RemoteIconData = RemoteIconData.fromMaterial("fitness_center");


    static readonly flag: RemoteIconData = RemoteIconData.fromMaterial("flag");


    static readonly flare: RemoteIconData = RemoteIconData.fromMaterial("flare");


    static readonly flash_auto: RemoteIconData = RemoteIconData.fromMaterial("flash_auto");


    static readonly flash_off: RemoteIconData = RemoteIconData.fromMaterial("flash_off");


    static readonly flash_on: RemoteIconData = RemoteIconData.fromMaterial("flash_on");


    static readonly flight: RemoteIconData = RemoteIconData.fromMaterial("flight");


    static readonly flight_land: RemoteIconData = RemoteIconData.fromMaterial("flight_land");


    static readonly flight_takeoff: RemoteIconData = RemoteIconData.fromMaterial("flight_takeoff");


    static readonly flip: RemoteIconData = RemoteIconData.fromMaterial("flip");


    static readonly flip_to_back: RemoteIconData = RemoteIconData.fromMaterial("flip_to_back");


    static readonly flip_to_front: RemoteIconData = RemoteIconData.fromMaterial("flip_to_front");


    static readonly folder: RemoteIconData = RemoteIconData.fromMaterial("folder");


    static readonly folder_open: RemoteIconData = RemoteIconData.fromMaterial("folder_open");


    static readonly folder_shared: RemoteIconData = RemoteIconData.fromMaterial("folder_shared");


    static readonly folder_special: RemoteIconData = RemoteIconData.fromMaterial("folder_special");


    static readonly font_download: RemoteIconData = RemoteIconData.fromMaterial("font_download");


    static readonly format_align_center: RemoteIconData = RemoteIconData.fromMaterial("format_align_center");


    static readonly format_align_justify: RemoteIconData = RemoteIconData.fromMaterial("format_align_justify");


    static readonly format_align_left: RemoteIconData = RemoteIconData.fromMaterial("format_align_left");


    static readonly format_align_right: RemoteIconData = RemoteIconData.fromMaterial("format_align_right");


    static readonly format_bold: RemoteIconData = RemoteIconData.fromMaterial("format_bold");


    static readonly format_clear: RemoteIconData = RemoteIconData.fromMaterial("format_clear");


    static readonly format_color_fill: RemoteIconData = RemoteIconData.fromMaterial("format_color_fill");


    static readonly format_color_reset: RemoteIconData = RemoteIconData.fromMaterial("format_color_reset");


    static readonly format_color_text: RemoteIconData = RemoteIconData.fromMaterial("format_color_text");


    static readonly format_indent_decrease: RemoteIconData = RemoteIconData.fromMaterial("format_indent_decrease");


    static readonly format_indent_increase: RemoteIconData = RemoteIconData.fromMaterial("format_indent_increase");


    static readonly format_italic: RemoteIconData = RemoteIconData.fromMaterial("format_italic");


    static readonly format_line_spacing: RemoteIconData = RemoteIconData.fromMaterial("format_line_spacing");


    static readonly format_list_bulleted: RemoteIconData = RemoteIconData.fromMaterial("format_list_bulleted");


    static readonly format_list_numbered: RemoteIconData = RemoteIconData.fromMaterial("format_list_numbered");


    static readonly format_list_numbered_rtl: RemoteIconData = RemoteIconData.fromMaterial("format_list_numbered_rtl");


    static readonly format_paint: RemoteIconData = RemoteIconData.fromMaterial("format_paint");


    static readonly format_quote: RemoteIconData = RemoteIconData.fromMaterial("format_quote");


    static readonly format_shapes: RemoteIconData = RemoteIconData.fromMaterial("format_shapes");


    static readonly format_size: RemoteIconData = RemoteIconData.fromMaterial("format_size");


    static readonly format_strikethrough: RemoteIconData = RemoteIconData.fromMaterial("format_strikethrough");


    static readonly format_textdirection_l_to_r: RemoteIconData = RemoteIconData.fromMaterial("format_textdirection_l_to_r");


    static readonly format_textdirection_r_to_l: RemoteIconData = RemoteIconData.fromMaterial("format_textdirection_r_to_l");


    static readonly format_underlined: RemoteIconData = RemoteIconData.fromMaterial("format_underlined");


    static readonly forum: RemoteIconData = RemoteIconData.fromMaterial("forum");


    static readonly forward: RemoteIconData = RemoteIconData.fromMaterial("forward");


    static readonly forward_10: RemoteIconData = RemoteIconData.fromMaterial("forward_10");


    static readonly forward_30: RemoteIconData = RemoteIconData.fromMaterial("forward_30");


    static readonly forward_5: RemoteIconData = RemoteIconData.fromMaterial("forward_5");


    static readonly free_breakfast: RemoteIconData = RemoteIconData.fromMaterial("free_breakfast");


    static readonly fullscreen: RemoteIconData = RemoteIconData.fromMaterial("fullscreen");


    static readonly fullscreen_exit: RemoteIconData = RemoteIconData.fromMaterial("fullscreen_exit");


    static readonly functions: RemoteIconData = RemoteIconData.fromMaterial("functions");


    static readonly g_translate: RemoteIconData = RemoteIconData.fromMaterial("g_translate");


    static readonly gamepad: RemoteIconData = RemoteIconData.fromMaterial("gamepad");


    static readonly games: RemoteIconData = RemoteIconData.fromMaterial("games");


    static readonly gavel: RemoteIconData = RemoteIconData.fromMaterial("gavel");


    static readonly gesture: RemoteIconData = RemoteIconData.fromMaterial("gesture");


    static readonly get_app: RemoteIconData = RemoteIconData.fromMaterial("get_app");


    static readonly gif: RemoteIconData = RemoteIconData.fromMaterial("gif");


    static readonly golf_course: RemoteIconData = RemoteIconData.fromMaterial("golf_course");


    static readonly gps_fixed: RemoteIconData = RemoteIconData.fromMaterial("gps_fixed");


    static readonly gps_not_fixed: RemoteIconData = RemoteIconData.fromMaterial("gps_not_fixed");


    static readonly gps_off: RemoteIconData = RemoteIconData.fromMaterial("gps_off");


    static readonly grade: RemoteIconData = RemoteIconData.fromMaterial("grade");


    static readonly gradient: RemoteIconData = RemoteIconData.fromMaterial("gradient");


    static readonly grain: RemoteIconData = RemoteIconData.fromMaterial("grain");


    static readonly graphic_eq: RemoteIconData = RemoteIconData.fromMaterial("graphic_eq");


    static readonly grid_off: RemoteIconData = RemoteIconData.fromMaterial("grid_off");


    static readonly grid_on: RemoteIconData = RemoteIconData.fromMaterial("grid_on");


    static readonly group: RemoteIconData = RemoteIconData.fromMaterial("group");


    static readonly group_add: RemoteIconData = RemoteIconData.fromMaterial("group_add");


    static readonly group_work: RemoteIconData = RemoteIconData.fromMaterial("group_work");


    static readonly hd: RemoteIconData = RemoteIconData.fromMaterial("hd");


    static readonly hdr_off: RemoteIconData = RemoteIconData.fromMaterial("hdr_off");


    static readonly hdr_on: RemoteIconData = RemoteIconData.fromMaterial("hdr_on");


    static readonly hdr_strong: RemoteIconData = RemoteIconData.fromMaterial("hdr_strong");


    static readonly hdr_weak: RemoteIconData = RemoteIconData.fromMaterial("hdr_weak");


    static readonly headset: RemoteIconData = RemoteIconData.fromMaterial("headset");


    static readonly headset_mic: RemoteIconData = RemoteIconData.fromMaterial("headset_mic");


    static readonly headset_off: RemoteIconData = RemoteIconData.fromMaterial("headset_off");


    static readonly healing: RemoteIconData = RemoteIconData.fromMaterial("healing");


    static readonly hearing: RemoteIconData = RemoteIconData.fromMaterial("hearing");


    static readonly help: RemoteIconData = RemoteIconData.fromMaterial("help");


    static readonly help_outline: RemoteIconData = RemoteIconData.fromMaterial("help_outline");


    static readonly high_quality: RemoteIconData = RemoteIconData.fromMaterial("high_quality");


    static readonly highlight: RemoteIconData = RemoteIconData.fromMaterial("highlight");


    static readonly highlight_off: RemoteIconData = RemoteIconData.fromMaterial("highlight_off");


    static readonly history: RemoteIconData = RemoteIconData.fromMaterial("history");


    static readonly home: RemoteIconData = RemoteIconData.fromMaterial("home");


    static readonly hot_tub: RemoteIconData = RemoteIconData.fromMaterial("hot_tub");


    static readonly hotel: RemoteIconData = RemoteIconData.fromMaterial("hotel");


    static readonly hourglass_empty: RemoteIconData = RemoteIconData.fromMaterial("hourglass_empty");


    static readonly hourglass_full: RemoteIconData = RemoteIconData.fromMaterial("hourglass_full");


    static readonly http: RemoteIconData = RemoteIconData.fromMaterial("http");


    static readonly https: RemoteIconData = RemoteIconData.fromMaterial("https");


    static readonly image: RemoteIconData = RemoteIconData.fromMaterial("image");


    static readonly image_aspect_ratio: RemoteIconData = RemoteIconData.fromMaterial("image_aspect_ratio");


    static readonly import_contacts: RemoteIconData = RemoteIconData.fromMaterial("import_contacts");


    static readonly import_export: RemoteIconData = RemoteIconData.fromMaterial("import_export");


    static readonly important_devices: RemoteIconData = RemoteIconData.fromMaterial("important_devices");


    static readonly inbox: RemoteIconData = RemoteIconData.fromMaterial("inbox");


    static readonly indeterminate_check_box: RemoteIconData = RemoteIconData.fromMaterial("indeterminate_check_box");


    static readonly info: RemoteIconData = RemoteIconData.fromMaterial("info");


    static readonly info_outline: RemoteIconData = RemoteIconData.fromMaterial("info_outline");


    static readonly input: RemoteIconData = RemoteIconData.fromMaterial("input");


    static readonly insert_chart: RemoteIconData = RemoteIconData.fromMaterial("insert_chart");


    static readonly insert_comment: RemoteIconData = RemoteIconData.fromMaterial("insert_comment");


    static readonly insert_drive_file: RemoteIconData = RemoteIconData.fromMaterial("insert_drive_file");


    static readonly insert_emoticon: RemoteIconData = RemoteIconData.fromMaterial("insert_emoticon");


    static readonly insert_invitation: RemoteIconData = RemoteIconData.fromMaterial("insert_invitation");


    static readonly insert_link: RemoteIconData = RemoteIconData.fromMaterial("insert_link");


    static readonly insert_photo: RemoteIconData = RemoteIconData.fromMaterial("insert_photo");


    static readonly invert_colors: RemoteIconData = RemoteIconData.fromMaterial("invert_colors");


    static readonly invert_colors_off: RemoteIconData = RemoteIconData.fromMaterial("invert_colors_off");


    static readonly iso: RemoteIconData = RemoteIconData.fromMaterial("iso");


    static readonly keyboard: RemoteIconData = RemoteIconData.fromMaterial("keyboard");


    static readonly keyboard_arrow_down: RemoteIconData = RemoteIconData.fromMaterial("keyboard_arrow_down");


    static readonly keyboard_arrow_left: RemoteIconData = RemoteIconData.fromMaterial("keyboard_arrow_left");


    static readonly keyboard_arrow_right: RemoteIconData = RemoteIconData.fromMaterial("keyboard_arrow_right");


    static readonly keyboard_arrow_up: RemoteIconData = RemoteIconData.fromMaterial("keyboard_arrow_up");


    static readonly keyboard_backspace: RemoteIconData = RemoteIconData.fromMaterial("keyboard_backspace");


    static readonly keyboard_capslock: RemoteIconData = RemoteIconData.fromMaterial("keyboard_capslock");


    static readonly keyboard_hide: RemoteIconData = RemoteIconData.fromMaterial("keyboard_hide");


    static readonly keyboard_return: RemoteIconData = RemoteIconData.fromMaterial("keyboard_return");


    static readonly keyboard_tab: RemoteIconData = RemoteIconData.fromMaterial("keyboard_tab");


    static readonly keyboard_voice: RemoteIconData = RemoteIconData.fromMaterial("keyboard_voice");


    static readonly kitchen: RemoteIconData = RemoteIconData.fromMaterial("kitchen");


    static readonly label: RemoteIconData = RemoteIconData.fromMaterial("label");


    static readonly label_important: RemoteIconData = RemoteIconData.fromMaterial("label_important");


    static readonly label_outline: RemoteIconData = RemoteIconData.fromMaterial("label_outline");


    static readonly landscape: RemoteIconData = RemoteIconData.fromMaterial("landscape");


    static readonly language: RemoteIconData = RemoteIconData.fromMaterial("language");


    static readonly laptop: RemoteIconData = RemoteIconData.fromMaterial("laptop");


    static readonly laptop_chromebook: RemoteIconData = RemoteIconData.fromMaterial("laptop_chromebook");


    static readonly laptop_mac: RemoteIconData = RemoteIconData.fromMaterial("laptop_mac");


    static readonly laptop_windows: RemoteIconData = RemoteIconData.fromMaterial("laptop_windows");


    static readonly last_page: RemoteIconData = RemoteIconData.fromMaterial("last_page");


    static readonly launch: RemoteIconData = RemoteIconData.fromMaterial("launch");


    static readonly layers: RemoteIconData = RemoteIconData.fromMaterial("layers");


    static readonly layers_clear: RemoteIconData = RemoteIconData.fromMaterial("layers_clear");


    static readonly leak_add: RemoteIconData = RemoteIconData.fromMaterial("leak_add");


    static readonly leak_remove: RemoteIconData = RemoteIconData.fromMaterial("leak_remove");


    static readonly lens: RemoteIconData = RemoteIconData.fromMaterial("lens");


    static readonly library_add: RemoteIconData = RemoteIconData.fromMaterial("library_add");


    static readonly library_books: RemoteIconData = RemoteIconData.fromMaterial("library_books");


    static readonly library_music: RemoteIconData = RemoteIconData.fromMaterial("library_music");


    static readonly lightbulb_outline: RemoteIconData = RemoteIconData.fromMaterial("lightbulb_outline");


    static readonly line_style: RemoteIconData = RemoteIconData.fromMaterial("line_style");


    static readonly line_weight: RemoteIconData = RemoteIconData.fromMaterial("line_weight");


    static readonly linear_scale: RemoteIconData = RemoteIconData.fromMaterial("linear_scale");


    static readonly link: RemoteIconData = RemoteIconData.fromMaterial("link");


    static readonly link_off: RemoteIconData = RemoteIconData.fromMaterial("link_off");


    static readonly linked_camera: RemoteIconData = RemoteIconData.fromMaterial("linked_camera");


    static readonly list: RemoteIconData = RemoteIconData.fromMaterial("list");


    static readonly live_help: RemoteIconData = RemoteIconData.fromMaterial("live_help");


    static readonly live_tv: RemoteIconData = RemoteIconData.fromMaterial("live_tv");


    static readonly local_activity: RemoteIconData = RemoteIconData.fromMaterial("local_activity");


    static readonly local_airport: RemoteIconData = RemoteIconData.fromMaterial("local_airport");


    static readonly local_atm: RemoteIconData = RemoteIconData.fromMaterial("local_atm");


    static readonly local_bar: RemoteIconData = RemoteIconData.fromMaterial("local_bar");


    static readonly local_cafe: RemoteIconData = RemoteIconData.fromMaterial("local_cafe");


    static readonly local_car_wash: RemoteIconData = RemoteIconData.fromMaterial("local_car_wash");


    static readonly local_convenience_store: RemoteIconData = RemoteIconData.fromMaterial("local_convenience_store");


    static readonly local_dining: RemoteIconData = RemoteIconData.fromMaterial("local_dining");


    static readonly local_drink: RemoteIconData = RemoteIconData.fromMaterial("local_drink");


    static readonly local_florist: RemoteIconData = RemoteIconData.fromMaterial("local_florist");


    static readonly local_gas_station: RemoteIconData = RemoteIconData.fromMaterial("local_gas_station");


    static readonly local_grocery_store: RemoteIconData = RemoteIconData.fromMaterial("local_grocery_store");


    static readonly local_hospital: RemoteIconData = RemoteIconData.fromMaterial("local_hospital");


    static readonly local_hotel: RemoteIconData = RemoteIconData.fromMaterial("local_hotel");


    static readonly local_laundry_service: RemoteIconData = RemoteIconData.fromMaterial("local_laundry_service");


    static readonly local_library: RemoteIconData = RemoteIconData.fromMaterial("local_library");


    static readonly local_mall: RemoteIconData = RemoteIconData.fromMaterial("local_mall");


    static readonly local_movies: RemoteIconData = RemoteIconData.fromMaterial("local_movies");


    static readonly local_offer: RemoteIconData = RemoteIconData.fromMaterial("local_offer");


    static readonly local_parking: RemoteIconData = RemoteIconData.fromMaterial("local_parking");


    static readonly local_pharmacy: RemoteIconData = RemoteIconData.fromMaterial("local_pharmacy");


    static readonly local_phone: RemoteIconData = RemoteIconData.fromMaterial("local_phone");


    static readonly local_pizza: RemoteIconData = RemoteIconData.fromMaterial("local_pizza");


    static readonly local_play: RemoteIconData = RemoteIconData.fromMaterial("local_play");


    static readonly local_post_office: RemoteIconData = RemoteIconData.fromMaterial("local_post_office");


    static readonly local_printshop: RemoteIconData = RemoteIconData.fromMaterial("local_printshop");


    static readonly local_see: RemoteIconData = RemoteIconData.fromMaterial("local_see");


    static readonly local_shipping: RemoteIconData = RemoteIconData.fromMaterial("local_shipping");


    static readonly local_taxi: RemoteIconData = RemoteIconData.fromMaterial("local_taxi");


    static readonly location_city: RemoteIconData = RemoteIconData.fromMaterial("location_city");


    static readonly location_disabled: RemoteIconData = RemoteIconData.fromMaterial("location_disabled");


    static readonly location_off: RemoteIconData = RemoteIconData.fromMaterial("location_off");


    static readonly location_on: RemoteIconData = RemoteIconData.fromMaterial("location_on");


    static readonly location_searching: RemoteIconData = RemoteIconData.fromMaterial("location_searching");


    static readonly lock: RemoteIconData = RemoteIconData.fromMaterial("lock");


    static readonly lock_open: RemoteIconData = RemoteIconData.fromMaterial("lock_open");


    static readonly lock_outline: RemoteIconData = RemoteIconData.fromMaterial("lock_outline");


    static readonly looks: RemoteIconData = RemoteIconData.fromMaterial("looks");


    static readonly looks_3: RemoteIconData = RemoteIconData.fromMaterial("looks_3");


    static readonly looks_4: RemoteIconData = RemoteIconData.fromMaterial("looks_4");


    static readonly looks_5: RemoteIconData = RemoteIconData.fromMaterial("looks_5");


    static readonly looks_6: RemoteIconData = RemoteIconData.fromMaterial("looks_6");


    static readonly looks_one: RemoteIconData = RemoteIconData.fromMaterial("looks_one");


    static readonly looks_two: RemoteIconData = RemoteIconData.fromMaterial("looks_two");


    static readonly loop: RemoteIconData = RemoteIconData.fromMaterial("loop");


    static readonly loupe: RemoteIconData = RemoteIconData.fromMaterial("loupe");


    static readonly low_priority: RemoteIconData = RemoteIconData.fromMaterial("low_priority");


    static readonly loyalty: RemoteIconData = RemoteIconData.fromMaterial("loyalty");


    static readonly mail: RemoteIconData = RemoteIconData.fromMaterial("mail");


    static readonly mail_outline: RemoteIconData = RemoteIconData.fromMaterial("mail_outline");


    static readonly map: RemoteIconData = RemoteIconData.fromMaterial("map");


    static readonly markunread: RemoteIconData = RemoteIconData.fromMaterial("markunread");


    static readonly markunread_mailbox: RemoteIconData = RemoteIconData.fromMaterial("markunread_mailbox");


    static readonly maximize: RemoteIconData = RemoteIconData.fromMaterial("maximize");


    static readonly memory: RemoteIconData = RemoteIconData.fromMaterial("memory");


    static readonly menu: RemoteIconData = RemoteIconData.fromMaterial("menu");


    static readonly merge_type: RemoteIconData = RemoteIconData.fromMaterial("merge_type");


    static readonly message: RemoteIconData = RemoteIconData.fromMaterial("message");


    static readonly mic: RemoteIconData = RemoteIconData.fromMaterial("mic");


    static readonly mic_none: RemoteIconData = RemoteIconData.fromMaterial("mic_none");


    static readonly mic_off: RemoteIconData = RemoteIconData.fromMaterial("mic_off");


    static readonly minimize: RemoteIconData = RemoteIconData.fromMaterial("minimize");


    static readonly missed_video_call: RemoteIconData = RemoteIconData.fromMaterial("missed_video_call");


    static readonly mms: RemoteIconData = RemoteIconData.fromMaterial("mms");


    static readonly mobile_screen_share: RemoteIconData = RemoteIconData.fromMaterial("mobile_screen_share");


    static readonly mode_comment: RemoteIconData = RemoteIconData.fromMaterial("mode_comment");


    static readonly mode_edit: RemoteIconData = RemoteIconData.fromMaterial("mode_edit");


    static readonly monetization_on: RemoteIconData = RemoteIconData.fromMaterial("monetization_on");


    static readonly money_off: RemoteIconData = RemoteIconData.fromMaterial("money_off");


    static readonly monochrome_photos: RemoteIconData = RemoteIconData.fromMaterial("monochrome_photos");


    static readonly mood: RemoteIconData = RemoteIconData.fromMaterial("mood");


    static readonly mood_bad: RemoteIconData = RemoteIconData.fromMaterial("mood_bad");


    static readonly more: RemoteIconData = RemoteIconData.fromMaterial("more");


    static readonly more_horiz: RemoteIconData = RemoteIconData.fromMaterial("more_horiz");


    static readonly more_vert: RemoteIconData = RemoteIconData.fromMaterial("more_vert");


    static readonly motorcycle: RemoteIconData = RemoteIconData.fromMaterial("motorcycle");


    static readonly mouse: RemoteIconData = RemoteIconData.fromMaterial("mouse");


    static readonly move_to_inbox: RemoteIconData = RemoteIconData.fromMaterial("move_to_inbox");


    static readonly movie: RemoteIconData = RemoteIconData.fromMaterial("movie");


    static readonly movie_creation: RemoteIconData = RemoteIconData.fromMaterial("movie_creation");


    static readonly movie_filter: RemoteIconData = RemoteIconData.fromMaterial("movie_filter");


    static readonly multiline_chart: RemoteIconData = RemoteIconData.fromMaterial("multiline_chart");


    static readonly music_note: RemoteIconData = RemoteIconData.fromMaterial("music_note");


    static readonly music_video: RemoteIconData = RemoteIconData.fromMaterial("music_video");


    static readonly my_location: RemoteIconData = RemoteIconData.fromMaterial("my_location");


    static readonly nature: RemoteIconData = RemoteIconData.fromMaterial("nature");


    static readonly nature_people: RemoteIconData = RemoteIconData.fromMaterial("nature_people");


    static readonly navigate_before: RemoteIconData = RemoteIconData.fromMaterial("navigate_before");


    static readonly navigate_next: RemoteIconData = RemoteIconData.fromMaterial("navigate_next");


    static readonly navigation: RemoteIconData = RemoteIconData.fromMaterial("navigation");


    static readonly near_me: RemoteIconData = RemoteIconData.fromMaterial("near_me");


    static readonly network_cell: RemoteIconData = RemoteIconData.fromMaterial("network_cell");


    static readonly network_check: RemoteIconData = RemoteIconData.fromMaterial("network_check");


    static readonly network_locked: RemoteIconData = RemoteIconData.fromMaterial("network_locked");


    static readonly network_wifi: RemoteIconData = RemoteIconData.fromMaterial("network_wifi");


    static readonly new_releases: RemoteIconData = RemoteIconData.fromMaterial("new_releases");


    static readonly next_week: RemoteIconData = RemoteIconData.fromMaterial("next_week");


    static readonly nfc: RemoteIconData = RemoteIconData.fromMaterial("nfc");


    static readonly no_encryption: RemoteIconData = RemoteIconData.fromMaterial("no_encryption");


    static readonly no_sim: RemoteIconData = RemoteIconData.fromMaterial("no_sim");


    static readonly not_interested: RemoteIconData = RemoteIconData.fromMaterial("not_interested");


    static readonly not_listed_location: RemoteIconData = RemoteIconData.fromMaterial("not_listed_location");


    static readonly note: RemoteIconData = RemoteIconData.fromMaterial("note");


    static readonly note_add: RemoteIconData = RemoteIconData.fromMaterial("note_add");


    static readonly notification_important: RemoteIconData = RemoteIconData.fromMaterial("notification_important");


    static readonly notifications: RemoteIconData = RemoteIconData.fromMaterial("notifications");


    static readonly notifications_active: RemoteIconData = RemoteIconData.fromMaterial("notifications_active");


    static readonly notifications_none: RemoteIconData = RemoteIconData.fromMaterial("notifications_none");


    static readonly notifications_off: RemoteIconData = RemoteIconData.fromMaterial("notifications_off");


    static readonly notifications_paused: RemoteIconData = RemoteIconData.fromMaterial("notifications_paused");


    static readonly offline_bolt: RemoteIconData = RemoteIconData.fromMaterial("offline_bolt");


    static readonly offline_pin: RemoteIconData = RemoteIconData.fromMaterial("offline_pin");


    static readonly ondemand_video: RemoteIconData = RemoteIconData.fromMaterial("ondemand_video");


    static readonly opacity: RemoteIconData = RemoteIconData.fromMaterial("opacity");


    static readonly open_in_browser: RemoteIconData = RemoteIconData.fromMaterial("open_in_browser");


    static readonly open_in_new: RemoteIconData = RemoteIconData.fromMaterial("open_in_new");


    static readonly open_with: RemoteIconData = RemoteIconData.fromMaterial("open_with");


    static readonly outlined_flag: RemoteIconData = RemoteIconData.fromMaterial("outlined_flag");


    static readonly pages: RemoteIconData = RemoteIconData.fromMaterial("pages");


    static readonly pageview: RemoteIconData = RemoteIconData.fromMaterial("pageview");


    static readonly palette: RemoteIconData = RemoteIconData.fromMaterial("palette");


    static readonly pan_tool: RemoteIconData = RemoteIconData.fromMaterial("pan_tool");


    static readonly panorama: RemoteIconData = RemoteIconData.fromMaterial("panorama");


    static readonly panorama_fish_eye: RemoteIconData = RemoteIconData.fromMaterial("panorama_fish_eye");


    static readonly panorama_horizontal: RemoteIconData = RemoteIconData.fromMaterial("panorama_horizontal");


    static readonly panorama_vertical: RemoteIconData = RemoteIconData.fromMaterial("panorama_vertical");


    static readonly panorama_wide_angle: RemoteIconData = RemoteIconData.fromMaterial("panorama_wide_angle");


    static readonly party_mode: RemoteIconData = RemoteIconData.fromMaterial("party_mode");


    static readonly pause: RemoteIconData = RemoteIconData.fromMaterial("pause");


    static readonly pause_circle_filled: RemoteIconData = RemoteIconData.fromMaterial("pause_circle_filled");


    static readonly pause_circle_outline: RemoteIconData = RemoteIconData.fromMaterial("pause_circle_outline");


    static readonly payment: RemoteIconData = RemoteIconData.fromMaterial("payment");


    static readonly people: RemoteIconData = RemoteIconData.fromMaterial("people");


    static readonly people_outline: RemoteIconData = RemoteIconData.fromMaterial("people_outline");


    static readonly perm_camera_mic: RemoteIconData = RemoteIconData.fromMaterial("perm_camera_mic");


    static readonly perm_contact_calendar: RemoteIconData = RemoteIconData.fromMaterial("perm_contact_calendar");


    static readonly perm_data_setting: RemoteIconData = RemoteIconData.fromMaterial("perm_data_setting");


    static readonly perm_device_information: RemoteIconData = RemoteIconData.fromMaterial("perm_device_information");


    static readonly perm_identity: RemoteIconData = RemoteIconData.fromMaterial("perm_identity");


    static readonly perm_media: RemoteIconData = RemoteIconData.fromMaterial("perm_media");


    static readonly perm_phone_msg: RemoteIconData = RemoteIconData.fromMaterial("perm_phone_msg");


    static readonly perm_scan_wifi: RemoteIconData = RemoteIconData.fromMaterial("perm_scan_wifi");


    static readonly person: RemoteIconData = RemoteIconData.fromMaterial("person");


    static readonly person_add: RemoteIconData = RemoteIconData.fromMaterial("person_add");


    static readonly person_outline: RemoteIconData = RemoteIconData.fromMaterial("person_outline");


    static readonly person_pin: RemoteIconData = RemoteIconData.fromMaterial("person_pin");


    static readonly person_pin_circle: RemoteIconData = RemoteIconData.fromMaterial("person_pin_circle");


    static readonly personal_video: RemoteIconData = RemoteIconData.fromMaterial("personal_video");


    static readonly pets: RemoteIconData = RemoteIconData.fromMaterial("pets");


    static readonly phone: RemoteIconData = RemoteIconData.fromMaterial("phone");


    static readonly phone_android: RemoteIconData = RemoteIconData.fromMaterial("phone_android");


    static readonly phone_bluetooth_speaker: RemoteIconData = RemoteIconData.fromMaterial("phone_bluetooth_speaker");


    static readonly phone_forwarded: RemoteIconData = RemoteIconData.fromMaterial("phone_forwarded");


    static readonly phone_in_talk: RemoteIconData = RemoteIconData.fromMaterial("phone_in_talk");


    static readonly phone_iphone: RemoteIconData = RemoteIconData.fromMaterial("phone_iphone");


    static readonly phone_locked: RemoteIconData = RemoteIconData.fromMaterial("phone_locked");


    static readonly phone_missed: RemoteIconData = RemoteIconData.fromMaterial("phone_missed");


    static readonly phone_paused: RemoteIconData = RemoteIconData.fromMaterial("phone_paused");


    static readonly phonelink: RemoteIconData = RemoteIconData.fromMaterial("phonelink");


    static readonly phonelink_erase: RemoteIconData = RemoteIconData.fromMaterial("phonelink_erase");


    static readonly phonelink_lock: RemoteIconData = RemoteIconData.fromMaterial("phonelink_lock");


    static readonly phonelink_off: RemoteIconData = RemoteIconData.fromMaterial("phonelink_off");


    static readonly phonelink_ring: RemoteIconData = RemoteIconData.fromMaterial("phonelink_ring");


    static readonly phonelink_setup: RemoteIconData = RemoteIconData.fromMaterial("phonelink_setup");


    static readonly photo: RemoteIconData = RemoteIconData.fromMaterial("photo");


    static readonly photo_album: RemoteIconData = RemoteIconData.fromMaterial("photo_album");


    static readonly photo_camera: RemoteIconData = RemoteIconData.fromMaterial("photo_camera");


    static readonly photo_filter: RemoteIconData = RemoteIconData.fromMaterial("photo_filter");


    static readonly photo_library: RemoteIconData = RemoteIconData.fromMaterial("photo_library");


    static readonly photo_size_select_actual: RemoteIconData = RemoteIconData.fromMaterial("photo_size_select_actual");


    static readonly photo_size_select_large: RemoteIconData = RemoteIconData.fromMaterial("photo_size_select_large");


    static readonly photo_size_select_small: RemoteIconData = RemoteIconData.fromMaterial("photo_size_select_small");


    static readonly picture_as_pdf: RemoteIconData = RemoteIconData.fromMaterial("picture_as_pdf");


    static readonly picture_in_picture: RemoteIconData = RemoteIconData.fromMaterial("picture_in_picture");


    static readonly picture_in_picture_alt: RemoteIconData = RemoteIconData.fromMaterial("picture_in_picture_alt");


    static readonly pie_chart: RemoteIconData = RemoteIconData.fromMaterial("pie_chart");


    static readonly pie_chart_outlined: RemoteIconData = RemoteIconData.fromMaterial("pie_chart_outlined");


    static readonly pin_drop: RemoteIconData = RemoteIconData.fromMaterial("pin_drop");


    static readonly place: RemoteIconData = RemoteIconData.fromMaterial("place");


    static readonly play_arrow: RemoteIconData = RemoteIconData.fromMaterial("play_arrow");


    static readonly play_circle_filled: RemoteIconData = RemoteIconData.fromMaterial("play_circle_filled");


    static readonly play_circle_outline: RemoteIconData = RemoteIconData.fromMaterial("play_circle_outline");


    static readonly play_for_work: RemoteIconData = RemoteIconData.fromMaterial("play_for_work");


    static readonly playlist_add: RemoteIconData = RemoteIconData.fromMaterial("playlist_add");


    static readonly playlist_add_check: RemoteIconData = RemoteIconData.fromMaterial("playlist_add_check");


    static readonly playlist_play: RemoteIconData = RemoteIconData.fromMaterial("playlist_play");


    static readonly plus_one: RemoteIconData = RemoteIconData.fromMaterial("plus_one");


    static readonly poll: RemoteIconData = RemoteIconData.fromMaterial("poll");


    static readonly polymer: RemoteIconData = RemoteIconData.fromMaterial("polymer");


    static readonly pool: RemoteIconData = RemoteIconData.fromMaterial("pool");


    static readonly portable_wifi_off: RemoteIconData = RemoteIconData.fromMaterial("portable_wifi_off");


    static readonly portrait: RemoteIconData = RemoteIconData.fromMaterial("portrait");


    static readonly power: RemoteIconData = RemoteIconData.fromMaterial("power");


    static readonly power_input: RemoteIconData = RemoteIconData.fromMaterial("power_input");


    static readonly power_settings_new: RemoteIconData = RemoteIconData.fromMaterial("power_settings_new");


    static readonly pregnant_woman: RemoteIconData = RemoteIconData.fromMaterial("pregnant_woman");


    static readonly present_to_all: RemoteIconData = RemoteIconData.fromMaterial("present_to_all");


    static readonly print: RemoteIconData = RemoteIconData.fromMaterial("print");


    static readonly priority_high: RemoteIconData = RemoteIconData.fromMaterial("priority_high");


    static readonly public: RemoteIconData = RemoteIconData.fromMaterial("public");


    static readonly publish: RemoteIconData = RemoteIconData.fromMaterial("publish");


    static readonly query_builder: RemoteIconData = RemoteIconData.fromMaterial("query_builder");


    static readonly question_answer: RemoteIconData = RemoteIconData.fromMaterial("question_answer");


    static readonly queue: RemoteIconData = RemoteIconData.fromMaterial("queue");


    static readonly queue_music: RemoteIconData = RemoteIconData.fromMaterial("queue_music");


    static readonly queue_play_next: RemoteIconData = RemoteIconData.fromMaterial("queue_play_next");


    static readonly radio: RemoteIconData = RemoteIconData.fromMaterial("radio");


    static readonly radio_button_checked: RemoteIconData = RemoteIconData.fromMaterial("radio_button_checked");


    static readonly radio_button_unchecked: RemoteIconData = RemoteIconData.fromMaterial("radio_button_unchecked");


    static readonly rate_review: RemoteIconData = RemoteIconData.fromMaterial("rate_review");


    static readonly receipt: RemoteIconData = RemoteIconData.fromMaterial("receipt");


    static readonly recent_actors: RemoteIconData = RemoteIconData.fromMaterial("recent_actors");


    static readonly record_voice_over: RemoteIconData = RemoteIconData.fromMaterial("record_voice_over");


    static readonly redeem: RemoteIconData = RemoteIconData.fromMaterial("redeem");


    static readonly redo: RemoteIconData = RemoteIconData.fromMaterial("redo");


    static readonly refresh: RemoteIconData = RemoteIconData.fromMaterial("refresh");


    static readonly remove: RemoteIconData = RemoteIconData.fromMaterial("remove");


    static readonly remove_circle: RemoteIconData = RemoteIconData.fromMaterial("remove_circle");


    static readonly remove_circle_outline: RemoteIconData = RemoteIconData.fromMaterial("remove_circle_outline");


    static readonly remove_from_queue: RemoteIconData = RemoteIconData.fromMaterial("remove_from_queue");


    static readonly remove_red_eye: RemoteIconData = RemoteIconData.fromMaterial("remove_red_eye");


    static readonly remove_shopping_cart: RemoteIconData = RemoteIconData.fromMaterial("remove_shopping_cart");


    static readonly reorder: RemoteIconData = RemoteIconData.fromMaterial("reorder");


    static readonly repeat: RemoteIconData = RemoteIconData.fromMaterial("repeat");


    static readonly repeat_one: RemoteIconData = RemoteIconData.fromMaterial("repeat_one");


    static readonly replay: RemoteIconData = RemoteIconData.fromMaterial("replay");


    static readonly replay_10: RemoteIconData = RemoteIconData.fromMaterial("replay_10");


    static readonly replay_30: RemoteIconData = RemoteIconData.fromMaterial("replay_30");


    static readonly replay_5: RemoteIconData = RemoteIconData.fromMaterial("replay_5");


    static readonly reply: RemoteIconData = RemoteIconData.fromMaterial("reply");


    static readonly reply_all: RemoteIconData = RemoteIconData.fromMaterial("reply_all");


    static readonly report: RemoteIconData = RemoteIconData.fromMaterial("report");


    static readonly report_off: RemoteIconData = RemoteIconData.fromMaterial("report_off");


    static readonly report_problem: RemoteIconData = RemoteIconData.fromMaterial("report_problem");


    static readonly restaurant: RemoteIconData = RemoteIconData.fromMaterial("restaurant");


    static readonly restaurant_menu: RemoteIconData = RemoteIconData.fromMaterial("restaurant_menu");


    static readonly restore: RemoteIconData = RemoteIconData.fromMaterial("restore");


    static readonly restore_from_trash: RemoteIconData = RemoteIconData.fromMaterial("restore_from_trash");


    static readonly restore_page: RemoteIconData = RemoteIconData.fromMaterial("restore_page");


    static readonly ring_volume: RemoteIconData = RemoteIconData.fromMaterial("ring_volume");


    static readonly room: RemoteIconData = RemoteIconData.fromMaterial("room");


    static readonly room_service: RemoteIconData = RemoteIconData.fromMaterial("room_service");


    static readonly rotate_90_degrees_ccw: RemoteIconData = RemoteIconData.fromMaterial("rotate_90_degrees_ccw");


    static readonly rotate_left: RemoteIconData = RemoteIconData.fromMaterial("rotate_left");


    static readonly rotate_right: RemoteIconData = RemoteIconData.fromMaterial("rotate_right");


    static readonly rounded_corner: RemoteIconData = RemoteIconData.fromMaterial("rounded_corner");


    static readonly router: RemoteIconData = RemoteIconData.fromMaterial("router");


    static readonly rowing: RemoteIconData = RemoteIconData.fromMaterial("rowing");


    static readonly rss_feed: RemoteIconData = RemoteIconData.fromMaterial("rss_feed");


    static readonly rv_hookup: RemoteIconData = RemoteIconData.fromMaterial("rv_hookup");


    static readonly satellite: RemoteIconData = RemoteIconData.fromMaterial("satellite");


    static readonly save: RemoteIconData = RemoteIconData.fromMaterial("save");


    static readonly save_alt: RemoteIconData = RemoteIconData.fromMaterial("save_alt");


    static readonly scanner: RemoteIconData = RemoteIconData.fromMaterial("scanner");


    static readonly scatter_plot: RemoteIconData = RemoteIconData.fromMaterial("scatter_plot");


    static readonly schedule: RemoteIconData = RemoteIconData.fromMaterial("schedule");


    static readonly school: RemoteIconData = RemoteIconData.fromMaterial("school");


    static readonly score: RemoteIconData = RemoteIconData.fromMaterial("score");


    static readonly screen_lock_landscape: RemoteIconData = RemoteIconData.fromMaterial("screen_lock_landscape");


    static readonly screen_lock_portrait: RemoteIconData = RemoteIconData.fromMaterial("screen_lock_portrait");


    static readonly screen_lock_rotation: RemoteIconData = RemoteIconData.fromMaterial("screen_lock_rotation");


    static readonly screen_rotation: RemoteIconData = RemoteIconData.fromMaterial("screen_rotation");


    static readonly screen_share: RemoteIconData = RemoteIconData.fromMaterial("screen_share");


    static readonly sd_card: RemoteIconData = RemoteIconData.fromMaterial("sd_card");


    static readonly sd_storage: RemoteIconData = RemoteIconData.fromMaterial("sd_storage");


    static readonly search: RemoteIconData = RemoteIconData.fromMaterial("search");


    static readonly security: RemoteIconData = RemoteIconData.fromMaterial("security");


    static readonly select_all: RemoteIconData = RemoteIconData.fromMaterial("select_all");


    static readonly send: RemoteIconData = RemoteIconData.fromMaterial("send");


    static readonly sentiment_dissatisfied: RemoteIconData = RemoteIconData.fromMaterial("sentiment_dissatisfied");


    static readonly sentiment_neutral: RemoteIconData = RemoteIconData.fromMaterial("sentiment_neutral");


    static readonly sentiment_satisfied: RemoteIconData = RemoteIconData.fromMaterial("sentiment_satisfied");


    static readonly sentiment_very_dissatisfied: RemoteIconData = RemoteIconData.fromMaterial("sentiment_very_dissatisfied");


    static readonly sentiment_very_satisfied: RemoteIconData = RemoteIconData.fromMaterial("sentiment_very_satisfied");


    static readonly settings: RemoteIconData = RemoteIconData.fromMaterial("settings");


    static readonly settings_applications: RemoteIconData = RemoteIconData.fromMaterial("settings_applications");


    static readonly settings_backup_restore: RemoteIconData = RemoteIconData.fromMaterial("settings_backup_restore");


    static readonly settings_bluetooth: RemoteIconData = RemoteIconData.fromMaterial("settings_bluetooth");


    static readonly settings_brightness: RemoteIconData = RemoteIconData.fromMaterial("settings_brightness");


    static readonly settings_cell: RemoteIconData = RemoteIconData.fromMaterial("settings_cell");


    static readonly settings_ethernet: RemoteIconData = RemoteIconData.fromMaterial("settings_ethernet");


    static readonly settings_input_antenna: RemoteIconData = RemoteIconData.fromMaterial("settings_input_antenna");


    static readonly settings_input_component: RemoteIconData = RemoteIconData.fromMaterial("settings_input_component");


    static readonly settings_input_composite: RemoteIconData = RemoteIconData.fromMaterial("settings_input_composite");


    static readonly settings_input_hdmi: RemoteIconData = RemoteIconData.fromMaterial("settings_input_hdmi");


    static readonly settings_input_svideo: RemoteIconData = RemoteIconData.fromMaterial("settings_input_svideo");


    static readonly settings_overscan: RemoteIconData = RemoteIconData.fromMaterial("settings_overscan");


    static readonly settings_phone: RemoteIconData = RemoteIconData.fromMaterial("settings_phone");


    static readonly settings_power: RemoteIconData = RemoteIconData.fromMaterial("settings_power");


    static readonly settings_remote: RemoteIconData = RemoteIconData.fromMaterial("settings_remote");


    static readonly settings_system_daydream: RemoteIconData = RemoteIconData.fromMaterial("settings_system_daydream");


    static readonly settings_voice: RemoteIconData = RemoteIconData.fromMaterial("settings_voice");


    static readonly share: RemoteIconData = RemoteIconData.fromMaterial("share");


    static readonly shop: RemoteIconData = RemoteIconData.fromMaterial("shop");


    static readonly shop_two: RemoteIconData = RemoteIconData.fromMaterial("shop_two");


    static readonly shopping_basket: RemoteIconData = RemoteIconData.fromMaterial("shopping_basket");


    static readonly shopping_cart: RemoteIconData = RemoteIconData.fromMaterial("shopping_cart");


    static readonly short_text: RemoteIconData = RemoteIconData.fromMaterial("short_text");


    static readonly show_chart: RemoteIconData = RemoteIconData.fromMaterial("show_chart");


    static readonly shuffle: RemoteIconData = RemoteIconData.fromMaterial("shuffle");


    static readonly shutter_speed: RemoteIconData = RemoteIconData.fromMaterial("shutter_speed");


    static readonly signal_cellular_4_bar: RemoteIconData = RemoteIconData.fromMaterial("signal_cellular_4_bar");


    static readonly signal_cellular_connected_no_internet_4_bar: RemoteIconData = RemoteIconData.fromMaterial("signal_cellular_connected_no_internet_4_bar");


    static readonly signal_cellular_no_sim: RemoteIconData = RemoteIconData.fromMaterial("signal_cellular_no_sim");


    static readonly signal_cellular_null: RemoteIconData = RemoteIconData.fromMaterial("signal_cellular_null");


    static readonly signal_cellular_off: RemoteIconData = RemoteIconData.fromMaterial("signal_cellular_off");


    static readonly signal_wifi_4_bar: RemoteIconData = RemoteIconData.fromMaterial("signal_wifi_4_bar");


    static readonly signal_wifi_4_bar_lock: RemoteIconData = RemoteIconData.fromMaterial("signal_wifi_4_bar_lock");


    static readonly signal_wifi_off: RemoteIconData = RemoteIconData.fromMaterial("signal_wifi_off");


    static readonly sim_card: RemoteIconData = RemoteIconData.fromMaterial("sim_card");


    static readonly sim_card_alert: RemoteIconData = RemoteIconData.fromMaterial("sim_card_alert");


    static readonly skip_next: RemoteIconData = RemoteIconData.fromMaterial("skip_next");


    static readonly skip_previous: RemoteIconData = RemoteIconData.fromMaterial("skip_previous");


    static readonly slideshow: RemoteIconData = RemoteIconData.fromMaterial("slideshow");


    static readonly slow_motion_video: RemoteIconData = RemoteIconData.fromMaterial("slow_motion_video");


    static readonly smartphone: RemoteIconData = RemoteIconData.fromMaterial("smartphone");


    static readonly smoke_free: RemoteIconData = RemoteIconData.fromMaterial("smoke_free");


    static readonly smoking_rooms: RemoteIconData = RemoteIconData.fromMaterial("smoking_rooms");


    static readonly sms: RemoteIconData = RemoteIconData.fromMaterial("sms");


    static readonly sms_failed: RemoteIconData = RemoteIconData.fromMaterial("sms_failed");


    static readonly snooze: RemoteIconData = RemoteIconData.fromMaterial("snooze");


    static readonly sort: RemoteIconData = RemoteIconData.fromMaterial("sort");


    static readonly sort_by_alpha: RemoteIconData = RemoteIconData.fromMaterial("sort_by_alpha");


    static readonly spa: RemoteIconData = RemoteIconData.fromMaterial("spa");


    static readonly space_bar: RemoteIconData = RemoteIconData.fromMaterial("space_bar");


    static readonly speaker: RemoteIconData = RemoteIconData.fromMaterial("speaker");


    static readonly speaker_group: RemoteIconData = RemoteIconData.fromMaterial("speaker_group");


    static readonly speaker_notes: RemoteIconData = RemoteIconData.fromMaterial("speaker_notes");


    static readonly speaker_notes_off: RemoteIconData = RemoteIconData.fromMaterial("speaker_notes_off");


    static readonly speaker_phone: RemoteIconData = RemoteIconData.fromMaterial("speaker_phone");


    static readonly spellcheck: RemoteIconData = RemoteIconData.fromMaterial("spellcheck");


    static readonly star: RemoteIconData = RemoteIconData.fromMaterial("star");


    static readonly star_border: RemoteIconData = RemoteIconData.fromMaterial("star_border");


    static readonly star_half: RemoteIconData = RemoteIconData.fromMaterial("star_half");


    static readonly stars: RemoteIconData = RemoteIconData.fromMaterial("stars");


    static readonly stay_current_landscape: RemoteIconData = RemoteIconData.fromMaterial("stay_current_landscape");


    static readonly stay_current_portrait: RemoteIconData = RemoteIconData.fromMaterial("stay_current_portrait");


    static readonly stay_primary_landscape: RemoteIconData = RemoteIconData.fromMaterial("stay_primary_landscape");


    static readonly stay_primary_portrait: RemoteIconData = RemoteIconData.fromMaterial("stay_primary_portrait");


    static readonly stop: RemoteIconData = RemoteIconData.fromMaterial("stop");


    static readonly stop_screen_share: RemoteIconData = RemoteIconData.fromMaterial("stop_screen_share");


    static readonly storage: RemoteIconData = RemoteIconData.fromMaterial("storage");


    static readonly store: RemoteIconData = RemoteIconData.fromMaterial("store");


    static readonly store_mall_directory: RemoteIconData = RemoteIconData.fromMaterial("store_mall_directory");


    static readonly straighten: RemoteIconData = RemoteIconData.fromMaterial("straighten");


    static readonly streetview: RemoteIconData = RemoteIconData.fromMaterial("streetview");


    static readonly strikethrough_s: RemoteIconData = RemoteIconData.fromMaterial("strikethrough_s");


    static readonly style: RemoteIconData = RemoteIconData.fromMaterial("style");


    static readonly subdirectory_arrow_left: RemoteIconData = RemoteIconData.fromMaterial("subdirectory_arrow_left");


    static readonly subdirectory_arrow_right: RemoteIconData = RemoteIconData.fromMaterial("subdirectory_arrow_right");


    static readonly subject: RemoteIconData = RemoteIconData.fromMaterial("subject");


    static readonly subscriptions: RemoteIconData = RemoteIconData.fromMaterial("subscriptions");


    static readonly subtitles: RemoteIconData = RemoteIconData.fromMaterial("subtitles");


    static readonly subway: RemoteIconData = RemoteIconData.fromMaterial("subway");


    static readonly supervised_user_circle: RemoteIconData = RemoteIconData.fromMaterial("supervised_user_circle");


    static readonly supervisor_account: RemoteIconData = RemoteIconData.fromMaterial("supervisor_account");


    static readonly surround_sound: RemoteIconData = RemoteIconData.fromMaterial("surround_sound");


    static readonly swap_calls: RemoteIconData = RemoteIconData.fromMaterial("swap_calls");


    static readonly swap_horiz: RemoteIconData = RemoteIconData.fromMaterial("swap_horiz");


    static readonly swap_horizontal_circle: RemoteIconData = RemoteIconData.fromMaterial("swap_horizontal_circle");


    static readonly swap_vert: RemoteIconData = RemoteIconData.fromMaterial("swap_vert");


    static readonly swap_vertical_circle: RemoteIconData = RemoteIconData.fromMaterial("swap_vertical_circle");


    static readonly switch_camera: RemoteIconData = RemoteIconData.fromMaterial("switch_camera");


    static readonly switch_video: RemoteIconData = RemoteIconData.fromMaterial("switch_video");


    static readonly sync: RemoteIconData = RemoteIconData.fromMaterial("sync");


    static readonly sync_disabled: RemoteIconData = RemoteIconData.fromMaterial("sync_disabled");


    static readonly sync_problem: RemoteIconData = RemoteIconData.fromMaterial("sync_problem");


    static readonly system_update: RemoteIconData = RemoteIconData.fromMaterial("system_update");


    static readonly system_update_alt: RemoteIconData = RemoteIconData.fromMaterial("system_update_alt");


    static readonly tab: RemoteIconData = RemoteIconData.fromMaterial("tab");


    static readonly tab_unselected: RemoteIconData = RemoteIconData.fromMaterial("tab_unselected");


    static readonly table_chart: RemoteIconData = RemoteIconData.fromMaterial("table_chart");


    static readonly tablet: RemoteIconData = RemoteIconData.fromMaterial("tablet");


    static readonly tablet_android: RemoteIconData = RemoteIconData.fromMaterial("tablet_android");


    static readonly tablet_mac: RemoteIconData = RemoteIconData.fromMaterial("tablet_mac");


    static readonly tag_faces: RemoteIconData = RemoteIconData.fromMaterial("tag_faces");


    static readonly tap_and_play: RemoteIconData = RemoteIconData.fromMaterial("tap_and_play");


    static readonly terrain: RemoteIconData = RemoteIconData.fromMaterial("terrain");


    static readonly text_fields: RemoteIconData = RemoteIconData.fromMaterial("text_fields");


    static readonly text_format: RemoteIconData = RemoteIconData.fromMaterial("text_format");


    static readonly text_rotate_up: RemoteIconData = RemoteIconData.fromMaterial("text_rotate_up");


    static readonly text_rotate_vertical: RemoteIconData = RemoteIconData.fromMaterial("text_rotate_vertical");


    static readonly text_rotation_angledown: RemoteIconData = RemoteIconData.fromMaterial("text_rotation_angledown");


    static readonly text_rotation_angleup: RemoteIconData = RemoteIconData.fromMaterial("text_rotation_angleup");


    static readonly text_rotation_down: RemoteIconData = RemoteIconData.fromMaterial("text_rotation_down");


    static readonly text_rotation_none: RemoteIconData = RemoteIconData.fromMaterial("text_rotation_none");


    static readonly textsms: RemoteIconData = RemoteIconData.fromMaterial("textsms");


    static readonly texture: RemoteIconData = RemoteIconData.fromMaterial("texture");


    static readonly theaters: RemoteIconData = RemoteIconData.fromMaterial("theaters");


    static readonly thumb_down: RemoteIconData = RemoteIconData.fromMaterial("thumb_down");


    static readonly thumb_up: RemoteIconData = RemoteIconData.fromMaterial("thumb_up");


    static readonly thumbs_up_down: RemoteIconData = RemoteIconData.fromMaterial("thumbs_up_down");


    static readonly time_to_leave: RemoteIconData = RemoteIconData.fromMaterial("time_to_leave");


    static readonly timelapse: RemoteIconData = RemoteIconData.fromMaterial("timelapse");


    static readonly timeline: RemoteIconData = RemoteIconData.fromMaterial("timeline");


    static readonly timer: RemoteIconData = RemoteIconData.fromMaterial("timer");


    static readonly timer_10: RemoteIconData = RemoteIconData.fromMaterial("timer_10");


    static readonly timer_3: RemoteIconData = RemoteIconData.fromMaterial("timer_3");


    static readonly timer_off: RemoteIconData = RemoteIconData.fromMaterial("timer_off");


    static readonly title: RemoteIconData = RemoteIconData.fromMaterial("title");


    static readonly toc: RemoteIconData = RemoteIconData.fromMaterial("toc");


    static readonly today: RemoteIconData = RemoteIconData.fromMaterial("today");


    static readonly toll: RemoteIconData = RemoteIconData.fromMaterial("toll");


    static readonly tonality: RemoteIconData = RemoteIconData.fromMaterial("tonality");


    static readonly touch_app: RemoteIconData = RemoteIconData.fromMaterial("touch_app");


    static readonly toys: RemoteIconData = RemoteIconData.fromMaterial("toys");


    static readonly track_changes: RemoteIconData = RemoteIconData.fromMaterial("track_changes");


    static readonly traffic: RemoteIconData = RemoteIconData.fromMaterial("traffic");


    static readonly train: RemoteIconData = RemoteIconData.fromMaterial("train");


    static readonly tram: RemoteIconData = RemoteIconData.fromMaterial("tram");


    static readonly transfer_within_a_station: RemoteIconData = RemoteIconData.fromMaterial("transfer_within_a_station");


    static readonly transform: RemoteIconData = RemoteIconData.fromMaterial("transform");


    static readonly transit_enterexit: RemoteIconData = RemoteIconData.fromMaterial("transit_enterexit");


    static readonly translate: RemoteIconData = RemoteIconData.fromMaterial("translate");


    static readonly trending_down: RemoteIconData = RemoteIconData.fromMaterial("trending_down");


    static readonly trending_flat: RemoteIconData = RemoteIconData.fromMaterial("trending_flat");


    static readonly trending_up: RemoteIconData = RemoteIconData.fromMaterial("trending_up");


    static readonly trip_origin: RemoteIconData = RemoteIconData.fromMaterial("trip_origin");


    static readonly tune: RemoteIconData = RemoteIconData.fromMaterial("tune");


    static readonly turned_in: RemoteIconData = RemoteIconData.fromMaterial("turned_in");


    static readonly turned_in_not: RemoteIconData = RemoteIconData.fromMaterial("turned_in_not");


    static readonly tv: RemoteIconData = RemoteIconData.fromMaterial("tv");


    static readonly unarchive: RemoteIconData = RemoteIconData.fromMaterial("unarchive");


    static readonly undo: RemoteIconData = RemoteIconData.fromMaterial("undo");


    static readonly unfold_less: RemoteIconData = RemoteIconData.fromMaterial("unfold_less");


    static readonly unfold_more: RemoteIconData = RemoteIconData.fromMaterial("unfold_more");


    static readonly update: RemoteIconData = RemoteIconData.fromMaterial("update");


    static readonly usb: RemoteIconData = RemoteIconData.fromMaterial("usb");


    static readonly verified_user: RemoteIconData = RemoteIconData.fromMaterial("verified_user");


    static readonly vertical_align_bottom: RemoteIconData = RemoteIconData.fromMaterial("vertical_align_bottom");


    static readonly vertical_align_center: RemoteIconData = RemoteIconData.fromMaterial("vertical_align_center");


    static readonly vertical_align_top: RemoteIconData = RemoteIconData.fromMaterial("vertical_align_top");


    static readonly vibration: RemoteIconData = RemoteIconData.fromMaterial("vibration");


    static readonly video_call: RemoteIconData = RemoteIconData.fromMaterial("video_call");


    static readonly video_label: RemoteIconData = RemoteIconData.fromMaterial("video_label");


    static readonly video_library: RemoteIconData = RemoteIconData.fromMaterial("video_library");


    static readonly videocam: RemoteIconData = RemoteIconData.fromMaterial("videocam");


    static readonly videocam_off: RemoteIconData = RemoteIconData.fromMaterial("videocam_off");


    static readonly videogame_asset: RemoteIconData = RemoteIconData.fromMaterial("videogame_asset");


    static readonly view_agenda: RemoteIconData = RemoteIconData.fromMaterial("view_agenda");


    static readonly view_array: RemoteIconData = RemoteIconData.fromMaterial("view_array");


    static readonly view_carousel: RemoteIconData = RemoteIconData.fromMaterial("view_carousel");


    static readonly view_column: RemoteIconData = RemoteIconData.fromMaterial("view_column");


    static readonly view_comfy: RemoteIconData = RemoteIconData.fromMaterial("view_comfy");


    static readonly view_compact: RemoteIconData = RemoteIconData.fromMaterial("view_compact");


    static readonly view_day: RemoteIconData = RemoteIconData.fromMaterial("view_day");


    static readonly view_headline: RemoteIconData = RemoteIconData.fromMaterial("view_headline");


    static readonly view_list: RemoteIconData = RemoteIconData.fromMaterial("view_list");


    static readonly view_module: RemoteIconData = RemoteIconData.fromMaterial("view_module");


    static readonly view_quilt: RemoteIconData = RemoteIconData.fromMaterial("view_quilt");


    static readonly view_stream: RemoteIconData = RemoteIconData.fromMaterial("view_stream");


    static readonly view_week: RemoteIconData = RemoteIconData.fromMaterial("view_week");


    static readonly vignette: RemoteIconData = RemoteIconData.fromMaterial("vignette");


    static readonly visibility: RemoteIconData = RemoteIconData.fromMaterial("visibility");


    static readonly visibility_off: RemoteIconData = RemoteIconData.fromMaterial("visibility_off");


    static readonly voice_chat: RemoteIconData = RemoteIconData.fromMaterial("voice_chat");


    static readonly voicemail: RemoteIconData = RemoteIconData.fromMaterial("voicemail");


    static readonly volume_down: RemoteIconData = RemoteIconData.fromMaterial("volume_down");


    static readonly volume_mute: RemoteIconData = RemoteIconData.fromMaterial("volume_mute");


    static readonly volume_off: RemoteIconData = RemoteIconData.fromMaterial("volume_off");


    static readonly volume_up: RemoteIconData = RemoteIconData.fromMaterial("volume_up");


    static readonly vpn_key: RemoteIconData = RemoteIconData.fromMaterial("vpn_key");


    static readonly vpn_lock: RemoteIconData = RemoteIconData.fromMaterial("vpn_lock");


    static readonly wallpaper: RemoteIconData = RemoteIconData.fromMaterial("wallpaper");


    static readonly warning: RemoteIconData = RemoteIconData.fromMaterial("warning");


    static readonly watch: RemoteIconData = RemoteIconData.fromMaterial("watch");


    static readonly watch_later: RemoteIconData = RemoteIconData.fromMaterial("watch_later");


    static readonly wb_auto: RemoteIconData = RemoteIconData.fromMaterial("wb_auto");


    static readonly wb_cloudy: RemoteIconData = RemoteIconData.fromMaterial("wb_cloudy");


    static readonly wb_incandescent: RemoteIconData = RemoteIconData.fromMaterial("wb_incandescent");


    static readonly wb_iridescent: RemoteIconData = RemoteIconData.fromMaterial("wb_iridescent");


    static readonly wb_sunny: RemoteIconData = RemoteIconData.fromMaterial("wb_sunny");


    static readonly wc: RemoteIconData = RemoteIconData.fromMaterial("wc");


    static readonly web: RemoteIconData = RemoteIconData.fromMaterial("web");


    static readonly web_asset: RemoteIconData = RemoteIconData.fromMaterial("web_asset");


    static readonly weekend: RemoteIconData = RemoteIconData.fromMaterial("weekend");


    static readonly whatshot: RemoteIconData = RemoteIconData.fromMaterial("whatshot");


    static readonly widgets: RemoteIconData = RemoteIconData.fromMaterial("widgets");


    static readonly wifi: RemoteIconData = RemoteIconData.fromMaterial("wifi");


    static readonly wifi_lock: RemoteIconData = RemoteIconData.fromMaterial("wifi_lock");


    static readonly wifi_tethering: RemoteIconData = RemoteIconData.fromMaterial("wifi_tethering");


    static readonly work: RemoteIconData = RemoteIconData.fromMaterial("work");


    static readonly wrap_text: RemoteIconData = RemoteIconData.fromMaterial("wrap_text");


    static readonly youtube_searched_for: RemoteIconData = RemoteIconData.fromMaterial("youtube_searched_for");


    static readonly zoom_in: RemoteIconData = RemoteIconData.fromMaterial("zoom_in");


    static readonly zoom_out: RemoteIconData = RemoteIconData.fromMaterial("zoom_out");


    static readonly zoom_out_map: RemoteIconData = RemoteIconData.fromMaterial("zoom_out_map");

}